name: Deploy to Railway

on:
  push:
    branches:
      - master  # or the branch you want to deploy

jobs:
  deploy:
    runs-on: windows-10
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node 20
      uses: actions/setup-node@v1
      with:
        node-version: 20.14.0

    - name: Install Railway CLI
      run: npm install -g @railway/cli

    - name: Deploy to Railway
      run: |
        railway up --service binar-challenge-ch6

    - name: Setup database
      run: railway run --service binar-challenge-ch6 npx prisma migrate deploy